# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:07:53+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class ApiDataRow(BaseModel):
    clicks: Optional[float] = None
    ctr: Optional[float] = None
    impressions: Optional[float] = None
    keys: Optional[List[str]] = None
    position: Optional[float] = None


class ApiDimensionFilter(BaseModel):
    dimension: Optional[str] = None
    expression: Optional[str] = None
    operator: Optional[str] = None


class ApiDimensionFilterGroup(BaseModel):
    filters: Optional[List[ApiDimensionFilter]] = None
    groupType: Optional[str] = None


class SearchAnalyticsQueryRequest(BaseModel):
    aggregationType: Optional[str] = Field(
        None,
        description='[Optional; Default is "auto"] How data is aggregated. If aggregated by property, all data for the same property is aggregated; if aggregated by page, all data is aggregated by canonical URI. If you filter or group by page, choose AUTO; otherwise you can aggregate either by property or by page, depending on how you want your data calculated; see  the help documentation to learn how data is calculated differently by site versus by page.\n\nNote: If you group or filter by page, you cannot aggregate by property.\n\nIf you specify any value other than AUTO, the aggregation type in the result will match the requested type, or if you request an invalid type, you will get an error. The API will never change your aggregation type if the requested type is invalid.',
    )
    dataState: Optional[str] = Field(
        None,
        description='[Optional] If "all" (case-insensitive), data will include fresh data. If "final" (case-insensitive) or if this parameter is omitted, the returned data will include only finalized data.',
    )
    dimensionFilterGroups: Optional[List[ApiDimensionFilterGroup]] = Field(
        None,
        description='[Optional] Zero or more filters to apply to the dimension grouping values; for example, \'query contains "buy"\' to see only data where the query string contains the substring "buy" (not case-sensitive). You can filter by a dimension without grouping by it.',
    )
    dimensions: Optional[List[str]] = Field(
        None,
        description='[Optional] Zero or more dimensions to group results by. Dimensions are the group-by values in the Search Analytics page. Dimensions are combined to create a unique row key for each row. Results are grouped in the order that you supply these dimensions.',
    )
    endDate: Optional[str] = Field(
        None,
        description='[Required] End date of the requested date range, in YYYY-MM-DD format, in PST (UTC - 8:00). Must be greater than or equal to the start date. This value is included in the range.',
    )
    rowLimit: Optional[int] = Field(
        None,
        description='[Optional; Default is 1000] The maximum number of rows to return. Must be a number from 1 to 5,000 (inclusive).',
    )
    searchType: Optional[str] = Field(
        None, description='[Optional; Default is "web"] The search type to filter for.'
    )
    startDate: Optional[str] = Field(
        None,
        description='[Required] Start date of the requested date range, in YYYY-MM-DD format, in PST time (UTC - 8:00). Must be less than or equal to the end date. This value is included in the range.',
    )
    startRow: Optional[int] = Field(
        None,
        description='[Optional; Default is 0] Zero-based index of the first row in the response. Must be a non-negative number.',
    )


class SearchAnalyticsQueryResponse(BaseModel):
    responseAggregationType: Optional[str] = Field(
        None, description='How the results were aggregated.'
    )
    rows: Optional[List[ApiDataRow]] = Field(
        None,
        description='A list of rows grouped by the key values in the order given in the query.',
    )


class WmxSite(BaseModel):
    permissionLevel: Optional[str] = Field(
        None, description="The user's permission level for the site."
    )
    siteUrl: Optional[str] = Field(None, description='The URL of the site.')


class WmxSitemapContent(BaseModel):
    indexed: Optional[str] = Field(
        None,
        description='The number of URLs from the sitemap that were indexed (of the content type).',
    )
    submitted: Optional[str] = Field(
        None, description='The number of URLs in the sitemap (of the content type).'
    )
    type: Optional[str] = Field(
        None,
        description='The specific type of content in this sitemap. For example: web.',
    )


class Alt(Enum):
    json = 'json'


class SitesListResponse(BaseModel):
    siteEntry: Optional[List[WmxSite]] = Field(
        None,
        description='Contains permission level information about a Search Console site. For more information, see Permissions in Search Console.',
    )


class WmxSitemap(BaseModel):
    contents: Optional[List[WmxSitemapContent]] = Field(
        None, description='The various content types in the sitemap.'
    )
    errors: Optional[str] = Field(
        None,
        description='Number of errors in the sitemap. These are issues with the sitemap itself that need to be fixed before it can be processed correctly.',
    )
    isPending: Optional[bool] = Field(
        None, description='If true, the sitemap has not been processed.'
    )
    isSitemapsIndex: Optional[bool] = Field(
        None, description='If true, the sitemap is a collection of sitemaps.'
    )
    lastDownloaded: Optional[datetime] = Field(
        None,
        description='Date & time in which this sitemap was last downloaded. Date format is in RFC 3339 format (yyyy-mm-dd).',
    )
    lastSubmitted: Optional[datetime] = Field(
        None,
        description='Date & time in which this sitemap was submitted. Date format is in RFC 3339 format (yyyy-mm-dd).',
    )
    path: Optional[str] = Field(None, description='The url of the sitemap.')
    type: Optional[str] = Field(
        None, description='The type of the sitemap. For example: rssFeed.'
    )
    warnings: Optional[str] = Field(
        None,
        description='Number of warnings for the sitemap. These are generally non-critical issues with URLs in the sitemaps.',
    )


class SitemapsListResponse(BaseModel):
    sitemap: Optional[List[WmxSitemap]] = Field(
        None,
        description='Contains detailed information about a specific URL submitted as a sitemap.',
    )
